# -*- coding: utf-8 -*-
"""object_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQkqAq3iXydLcyXMIKmIzfi-PVUieGp0
"""

from imageai.Detection import ObjectDetection

detector = ObjectDetection()

model_path = "/models/yolo-tiny.h5"
output_path = "/result/newimage.jpg"

detector.setModelTypeAsTinyYOLOv3()

detector.setModelPath(model_path)
detector.loadModel()

detection = detector.detectObjectsFromImage(input_image=input_path, output_image_path=output_path)

for eachItem in detection:
    print(eachItem["name"] , " : ", eachItem["percentage_probability"])